name: SuperBuildBattle
main: io.github.galaipa.bb.SuperBuildBattle
version: 4.5
author: Galaipa 
description: BuildBattle minigame plugin
softdepend: [WorldEdit,WorldGuard,Vault,PlayerPoints]
commands:
  buildbattle:
    description: BuildBattle main command
    usage: /<command>  
    aliases: [bb]
  buildbattleadmin:
    description: BuildBattle main command
    usage: /<command>  
    aliases: [bbadmin]  
permissions:
  bb.*:
        description: Gives access to all commands
        children:
            bb.join: true
  bb.user:
    description: Perm to use all user commands
    default: true
  bb.admin:
    description: Perm to use /buildbattleadmin commands
    default: op